// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: utils/plugins/gRPCLoader/gRPC.proto

package grpcloader

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InitializeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 插件注册方法请求
type RegisterMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*MethodDef           `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMethodsRequest) Reset() {
	*x = RegisterMethodsRequest{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMethodsRequest) ProtoMessage() {}

func (x *RegisterMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMethodsRequest.ProtoReflect.Descriptor instead.
func (*RegisterMethodsRequest) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMethodsRequest) GetMethods() []*MethodDef {
	if x != nil {
		return x.Methods
	}
	return nil
}

// 服务器返回可用方法列表
type AvailableMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*MethodDef           `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableMethodsResponse) Reset() {
	*x = AvailableMethodsResponse{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableMethodsResponse) ProtoMessage() {}

func (x *AvailableMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableMethodsResponse.ProtoReflect.Descriptor instead.
func (*AvailableMethodsResponse) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{2}
}

func (x *AvailableMethodsResponse) GetMethods() []*MethodDef {
	if x != nil {
		return x.Methods
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []*Arg                 `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=commandId,proto3" json:"commandId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type UnregisterMethods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []string               `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterMethods) Reset() {
	*x = UnregisterMethods{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterMethods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterMethods) ProtoMessage() {}

func (x *UnregisterMethods) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterMethods.ProtoReflect.Descriptor instead.
func (*UnregisterMethods) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterMethods) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type MethodDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgsNames     []*Arg                 `protobuf:"bytes,2,rep,name=args_names,json=argsNames,proto3" json:"args_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodDef) Reset() {
	*x = MethodDef{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodDef) ProtoMessage() {}

func (x *MethodDef) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodDef.ProtoReflect.Descriptor instead.
func (*MethodDef) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{5}
}

func (x *MethodDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodDef) GetArgsNames() []*Arg {
	if x != nil {
		return x.ArgsNames
	}
	return nil
}

type Verify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify) Reset() {
	*x = Verify{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify) ProtoMessage() {}

func (x *Verify) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify.ProtoReflect.Descriptor instead.
func (*Verify) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{6}
}

func (x *Verify) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []*Arg                 `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{7}
}

func (x *Args) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

type Arg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Arg           []byte                 `protobuf:"bytes,3,opt,name=arg,proto3" json:"arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arg) Reset() {
	*x = Arg{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg) ProtoMessage() {}

func (x *Arg) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg.ProtoReflect.Descriptor instead.
func (*Arg) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{8}
}

func (x *Arg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Arg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Arg) GetArg() []byte {
	if x != nil {
		return x.Arg
	}
	return nil
}

type CallMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Args          []*Arg                 `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallMethod) Reset() {
	*x = CallMethod{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallMethod) ProtoMessage() {}

func (x *CallMethod) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallMethod.ProtoReflect.Descriptor instead.
func (*CallMethod) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{9}
}

func (x *CallMethod) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallMethod) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

type ReturnAndError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReturnValue   string                 `protobuf:"bytes,2,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnAndError) Reset() {
	*x = ReturnAndError{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnAndError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAndError) ProtoMessage() {}

func (x *ReturnAndError) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAndError.ProtoReflect.Descriptor instead.
func (*ReturnAndError) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{10}
}

func (x *ReturnAndError) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReturnAndError) GetReturnValue() string {
	if x != nil {
		return x.ReturnValue
	}
	return ""
}

func (x *ReturnAndError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP(), []int{12}
}

var File_utils_plugins_gRPCLoader_gRPC_proto protoreflect.FileDescriptor

const file_utils_plugins_gRPCLoader_gRPC_proto_rawDesc = "" +
	"\n" +
	"#utils/plugins/gRPCLoader/gRPC.proto\">\n" +
	"\x12InitializeResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\">\n" +
	"\x16RegisterMethodsRequest\x12$\n" +
	"\amethods\x18\x01 \x03(\v2\n" +
	".MethodDefR\amethods\"@\n" +
	"\x18AvailableMethodsResponse\x12$\n" +
	"\amethods\x18\x01 \x03(\v2\n" +
	".MethodDefR\amethods\"[\n" +
	"\aCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x18\n" +
	"\x04args\x18\x02 \x03(\v2\x04.ArgR\x04args\x12\x1c\n" +
	"\tcommandId\x18\x03 \x01(\tR\tcommandId\"-\n" +
	"\x11UnregisterMethods\x12\x18\n" +
	"\amethods\x18\x01 \x03(\tR\amethods\"D\n" +
	"\tMethodDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\n" +
	"args_names\x18\x02 \x03(\v2\x04.ArgR\targsNames\"\x18\n" +
	"\x06Verify\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x04Args\x12\x18\n" +
	"\x04args\x18\x01 \x03(\v2\x04.ArgR\x04args\"?\n" +
	"\x03Arg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03arg\x18\x03 \x01(\fR\x03arg\">\n" +
	"\n" +
	"CallMethod\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\x04args\x18\x02 \x03(\v2\x04.ArgR\x04args\"c\n" +
	"\x0eReturnAndError\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\freturn_value\x18\x02 \x01(\tR\vreturnValue\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x1d\n" +
	"\x05Error\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\a\n" +
	"\x05Empty2\x80\x02\n" +
	"\rpluginService\x12+\n" +
	"\n" +
	"Initialize\x12\x06.Empty\x1a\x13.InitializeResponse\"\x00\x12\x1b\n" +
	"\x06UnLoad\x12\a.Verify\x1a\x06.Error\"\x00\x12M\n" +
	"\x15RegisterPluginMethods\x12\x17.RegisterMethodsRequest\x1a\x19.AvailableMethodsResponse\"\x00\x12,\n" +
	"\x10NewCommandStream\x12\b.Command\x1a\b.Command\"\x00(\x010\x01\x12(\n" +
	"\x10CallServerMethod\x12\v.CallMethod\x1a\x05.Args\"\x00B.Z,LiteBlog/utils/plugins/gRPCLoader/grpcloaderb\x06proto3"

var (
	file_utils_plugins_gRPCLoader_gRPC_proto_rawDescOnce sync.Once
	file_utils_plugins_gRPCLoader_gRPC_proto_rawDescData []byte
)

func file_utils_plugins_gRPCLoader_gRPC_proto_rawDescGZIP() []byte {
	file_utils_plugins_gRPCLoader_gRPC_proto_rawDescOnce.Do(func() {
		file_utils_plugins_gRPCLoader_gRPC_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utils_plugins_gRPCLoader_gRPC_proto_rawDesc), len(file_utils_plugins_gRPCLoader_gRPC_proto_rawDesc)))
	})
	return file_utils_plugins_gRPCLoader_gRPC_proto_rawDescData
}

var file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_utils_plugins_gRPCLoader_gRPC_proto_goTypes = []any{
	(*InitializeResponse)(nil),       // 0: InitializeResponse
	(*RegisterMethodsRequest)(nil),   // 1: RegisterMethodsRequest
	(*AvailableMethodsResponse)(nil), // 2: AvailableMethodsResponse
	(*Command)(nil),                  // 3: Command
	(*UnregisterMethods)(nil),        // 4: UnregisterMethods
	(*MethodDef)(nil),                // 5: MethodDef
	(*Verify)(nil),                   // 6: Verify
	(*Args)(nil),                     // 7: Args
	(*Arg)(nil),                      // 8: Arg
	(*CallMethod)(nil),               // 9: CallMethod
	(*ReturnAndError)(nil),           // 10: ReturnAndError
	(*Error)(nil),                    // 11: Error
	(*Empty)(nil),                    // 12: Empty
}
var file_utils_plugins_gRPCLoader_gRPC_proto_depIdxs = []int32{
	5,  // 0: RegisterMethodsRequest.methods:type_name -> MethodDef
	5,  // 1: AvailableMethodsResponse.methods:type_name -> MethodDef
	8,  // 2: Command.args:type_name -> Arg
	8,  // 3: MethodDef.args_names:type_name -> Arg
	8,  // 4: Args.args:type_name -> Arg
	8,  // 5: CallMethod.args:type_name -> Arg
	12, // 6: pluginService.Initialize:input_type -> Empty
	6,  // 7: pluginService.UnLoad:input_type -> Verify
	1,  // 8: pluginService.RegisterPluginMethods:input_type -> RegisterMethodsRequest
	3,  // 9: pluginService.NewCommandStream:input_type -> Command
	9,  // 10: pluginService.CallServerMethod:input_type -> CallMethod
	0,  // 11: pluginService.Initialize:output_type -> InitializeResponse
	11, // 12: pluginService.UnLoad:output_type -> Error
	2,  // 13: pluginService.RegisterPluginMethods:output_type -> AvailableMethodsResponse
	3,  // 14: pluginService.NewCommandStream:output_type -> Command
	7,  // 15: pluginService.CallServerMethod:output_type -> Args
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_utils_plugins_gRPCLoader_gRPC_proto_init() }
func file_utils_plugins_gRPCLoader_gRPC_proto_init() {
	if File_utils_plugins_gRPCLoader_gRPC_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utils_plugins_gRPCLoader_gRPC_proto_rawDesc), len(file_utils_plugins_gRPCLoader_gRPC_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utils_plugins_gRPCLoader_gRPC_proto_goTypes,
		DependencyIndexes: file_utils_plugins_gRPCLoader_gRPC_proto_depIdxs,
		MessageInfos:      file_utils_plugins_gRPCLoader_gRPC_proto_msgTypes,
	}.Build()
	File_utils_plugins_gRPCLoader_gRPC_proto = out.File
	file_utils_plugins_gRPCLoader_gRPC_proto_goTypes = nil
	file_utils_plugins_gRPCLoader_gRPC_proto_depIdxs = nil
}
