// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: utils/plugins/gRPCLoader/gRPC.proto

package grpcloader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Initialize_FullMethodName            = "/pluginService/Initialize"
	PluginService_UnLoad_FullMethodName                = "/pluginService/UnLoad"
	PluginService_RegisterPluginMethods_FullMethodName = "/pluginService/RegisterPluginMethods"
	PluginService_NewCommandStream_FullMethodName      = "/pluginService/NewCommandStream"
	PluginService_CallServerMethod_FullMethodName      = "/pluginService/CallServerMethod"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	Initialize(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InitializeResponse, error)
	UnLoad(ctx context.Context, in *Verify, opts ...grpc.CallOption) (*Error, error)
	// 插件注册其方法，服务器返回可调用的公共方法列表
	RegisterPluginMethods(ctx context.Context, in *RegisterMethodsRequest, opts ...grpc.CallOption) (*AvailableMethodsResponse, error)
	NewCommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Command, Command], error)
	CallServerMethod(ctx context.Context, in *CallMethod, opts ...grpc.CallOption) (*Args, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Initialize(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, PluginService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) UnLoad(ctx context.Context, in *Verify, opts ...grpc.CallOption) (*Error, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Error)
	err := c.cc.Invoke(ctx, PluginService_UnLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) RegisterPluginMethods(ctx context.Context, in *RegisterMethodsRequest, opts ...grpc.CallOption) (*AvailableMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailableMethodsResponse)
	err := c.cc.Invoke(ctx, PluginService_RegisterPluginMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) NewCommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Command, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginService_ServiceDesc.Streams[0], PluginService_NewCommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Command, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginService_NewCommandStreamClient = grpc.BidiStreamingClient[Command, Command]

func (c *pluginServiceClient) CallServerMethod(ctx context.Context, in *CallMethod, opts ...grpc.CallOption) (*Args, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Args)
	err := c.cc.Invoke(ctx, PluginService_CallServerMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
type PluginServiceServer interface {
	Initialize(context.Context, *Empty) (*InitializeResponse, error)
	UnLoad(context.Context, *Verify) (*Error, error)
	// 插件注册其方法，服务器返回可调用的公共方法列表
	RegisterPluginMethods(context.Context, *RegisterMethodsRequest) (*AvailableMethodsResponse, error)
	NewCommandStream(grpc.BidiStreamingServer[Command, Command]) error
	CallServerMethod(context.Context, *CallMethod) (*Args, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Initialize(context.Context, *Empty) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedPluginServiceServer) UnLoad(context.Context, *Verify) (*Error, error) {
	return nil, status.Error(codes.Unimplemented, "method UnLoad not implemented")
}
func (UnimplementedPluginServiceServer) RegisterPluginMethods(context.Context, *RegisterMethodsRequest) (*AvailableMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPluginMethods not implemented")
}
func (UnimplementedPluginServiceServer) NewCommandStream(grpc.BidiStreamingServer[Command, Command]) error {
	return status.Error(codes.Unimplemented, "method NewCommandStream not implemented")
}
func (UnimplementedPluginServiceServer) CallServerMethod(context.Context, *CallMethod) (*Args, error) {
	return nil, status.Error(codes.Unimplemented, "method CallServerMethod not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Initialize(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_UnLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Verify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).UnLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_UnLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).UnLoad(ctx, req.(*Verify))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_RegisterPluginMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).RegisterPluginMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_RegisterPluginMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).RegisterPluginMethods(ctx, req.(*RegisterMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_NewCommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginServiceServer).NewCommandStream(&grpc.GenericServerStream[Command, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginService_NewCommandStreamServer = grpc.BidiStreamingServer[Command, Command]

func _PluginService_CallServerMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CallServerMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_CallServerMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CallServerMethod(ctx, req.(*CallMethod))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _PluginService_Initialize_Handler,
		},
		{
			MethodName: "UnLoad",
			Handler:    _PluginService_UnLoad_Handler,
		},
		{
			MethodName: "RegisterPluginMethods",
			Handler:    _PluginService_RegisterPluginMethods_Handler,
		},
		{
			MethodName: "CallServerMethod",
			Handler:    _PluginService_CallServerMethod_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NewCommandStream",
			Handler:       _PluginService_NewCommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "utils/plugins/gRPCLoader/gRPC.proto",
}
